llm:
  # The user should edit this line with their model's ID
  model_id: "ollama_chat/llama3.2:3b"
  # The user should edit this line with their model's URL
  api_base: "PASTE_YOUR_MODEL_URL_HERE"
  # The user should edit this line with appropriate context length based on their system specifications
  num_ctx: 24576

agent:
  max_steps: 6
  verbosity_level: 2

prompts_file: "prompts.yaml"